name: labop-scheduler
channels:
  - defaults
dependencies:
  - pip=25.2=pyhc872135_1
  - python=3.13.5
  - python_abi=3.13
  - wheel=0.45.1
  - pip:
      - numpy==2.3.4
      - pandas==2.3.3
      - pulp==3.3.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - six==1.17.0
      - tzdata==2025.2
prefix: /Users/sifatulislamanindho/opt/anaconda3/envs/labop-scheduler
